// Configuration - Auto-generated by deploy-frontend.sh
// Update these values after deployment

const API_ENDPOINT = 'YOUR_API_ENDPOINT_HERE';

// Knowledge Base ID - auto-populated during deployment if available
// Students can also enter this manually in the UI
const DEFAULT_KB_ID = '';
