// Configuration - Auto-generated by setup.sh
// Generated: Fri Jan 30 09:58:36 EST 2026

const API_ENDPOINT = 'https://gyfgveshzi.execute-api.us-east-1.amazonaws.com/prod';

// Knowledge Base ID - auto-populated if found during deployment
const DEFAULT_KB_ID = 'YOWX7BAG2R';
