// Configuration - Auto-generated by setup.sh
// Generated: Thu Jan 30 2026

const API_ENDPOINT = 'https://ldcq4926j3.execute-api.us-east-1.amazonaws.com/prod';

// Knowledge Base ID - auto-populated if found during deployment
const DEFAULT_KB_ID = 'ZHQ8T1VW6Q';
