#!/bin/bash

# =============================================================================
# Deploy Frontend to S3
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
PROJECT_NAME="${PROJECT_NAME:-rag-pipeline}"
REGION="${AWS_REGION:-us-east-1}"
STACK_NAME="${PROJECT_NAME}-stack"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

echo -e "${YELLOW}Deploying RAG Playground Frontend...${NC}"

# Get API endpoint from CloudFormation
API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name $STACK_NAME \
    --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" \
    --output text --region $REGION 2>/dev/null)

if [ -z "$API_ENDPOINT" ] || [ "$API_ENDPOINT" == "None" ]; then
    echo -e "${RED}❌ Could not get API endpoint from CloudFormation${NC}"
    echo "Make sure the stack is deployed first: cd ../cloudformation && ./deploy.sh"
    exit 1
fi

echo "API Endpoint: $API_ENDPOINT"

# Try to get Knowledge Base ID if it exists
KB_ID=""
KB_IDS=$(aws bedrock-agent list-knowledge-bases \
    --query "knowledgeBaseSummaries[?contains(name, '${PROJECT_NAME}')].knowledgeBaseId" \
    --output text --region $REGION 2>/dev/null || echo "")

if [ -n "$KB_IDS" ] && [ "$KB_IDS" != "None" ]; then
    # Take the first KB ID if multiple exist
    KB_ID=$(echo $KB_IDS | awk '{print $1}')
    echo "Knowledge Base ID: $KB_ID"
else
    echo -e "${YELLOW}⚠️  No Knowledge Base found. Students will need to enter KB ID manually.${NC}"
fi

# Generate config.js with API endpoint and optional KB ID
cat > config.js << EOF
// Configuration - Auto-generated by deploy-frontend.sh
// API Endpoint from CloudFormation stack: ${STACK_NAME}
// Generated: $(date)

const API_ENDPOINT = '${API_ENDPOINT}';

// Knowledge Base ID - auto-populated if found during deployment
// Students can also enter/override this manually in the UI
const DEFAULT_KB_ID = '${KB_ID}';
EOF

echo -e "${GREEN}✓ Generated config.js${NC}"

# Get frontend bucket name
FRONTEND_BUCKET="${PROJECT_NAME}-frontend-${ACCOUNT_ID}-${REGION}"

# Upload frontend files
echo "Uploading frontend files to s3://${FRONTEND_BUCKET}/"
aws s3 sync . s3://${FRONTEND_BUCKET}/ \
    --exclude "deploy-frontend.sh" \
    --exclude ".DS_Store" \
    --region $REGION

echo -e "${GREEN}✓ Frontend deployed${NC}"

# Get website URL
WEBSITE_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME \
    --query "Stacks[0].Outputs[?OutputKey=='FrontendURL'].OutputValue" \
    --output text --region $REGION)

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  Frontend Deployment Complete!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo -e "Frontend URL: ${YELLOW}${WEBSITE_URL}${NC}"
if [ -n "$KB_ID" ]; then
    echo -e "Knowledge Base ID: ${YELLOW}${KB_ID}${NC} (auto-populated)"
fi
echo ""
echo "Next steps:"
echo "1. Open the URL above in your browser"
if [ -z "$KB_ID" ]; then
    echo "2. Create a Knowledge Base in Bedrock console"
    echo "3. Enter your Knowledge Base ID in the UI"
fi
echo "4. Start experimenting with prompts!"
